server:
  port: 9090

spring:
  config:
    import: env.yml
  datasource:
    url: jdbc:postgresql://${SERVER_ADDRESS}:${POSTGRESQL.PORT}/relpl
    username: ${POSTGRESQL.NAME}
    password: ${POSTGRESQL.PASSWORD}
    driver-class-name: org.postgresql.Driver
  data.mongodb:
    host: ${SERVER_ADDRESS}
    port: ${MONGODB.PORT}
    database: ${MONGODB.NAME}
  redis:
    host: ${SERVER_ADDRESS}
    port: ${REDIS.PORT}

tmap:
  api:
    key: 0ttiY8tbMp6yynwSOXkfl3EkQnU7rXO877tz4cxX