server:
  port: 9090

spring:
  config:
    import: env.yml
  datasource:
    url: ENC(Ap/qfYoQ8OOVNCxYSR0Pmmqi54bW6IlAQbi+qQu/GgG51cjwKTPIY0yirro5bubHHSxr0MeR4+k=)
    username: ENC(iCKopFxndqUdCpf1XdlvKg==)
    password: ENC(wrJtZ/9N6aB0LpFzgVks3xk+FEk9fvtY1obs0Q394G8=)
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      url: ENC(t0R6DFzkBkZG9v5Xy1otnVi52dcn4XqDqwHV9NpUKXJqYnzACRESFTn1Be+2o064)
      host: ENC(vewwyQ0zMOe77WvwzphNSqF0vAjbkvGP+mkABZCw8to=)
      port: 27017
      database: ENC(QYRSKr0uZOD+6mFChXcyMg==)
    redis:
      host: ENC(lqIzI0VbWenMVmGDjODMtfaIxoiK08DbDKPHc8bXRlA=)
      port: 6379

tmap:
  api:
    key: ENC(j3VH+078nbLoa1HuTYtNVreeXtj/cODQErEpIUC/NcckXD3SYyhfraK8uCDhTdc3ZCQdbSbDSKYq2/kZPpWQuUpDODD9mggw)

cloud:
  aws:
    s3:
      bucket: ENC(D3WremaoJraLKEONkOC/jg==)
      base-url: ENC(Uy/GzWij/acXMHP0+qXHxVBzv4UaNmzgWy/cm11ugTI5knpds9gNlgCeXUZ9WPNnxXJg+r8hp+s=)
    credentials:
      access-key: ENC(EZIkbuGlEWiYVEcqEWH7nis9QKLo7rhnsoRy16DwU1s=)
      secret-key: ENC(TxoY84Jj/3l2kvMtq67vW1Ee2l6HlSR7N81MNWKZLJaBIoI4LMssLe9o3QBICPOe6uSF34UhXY0=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false