server:
  port: 9090

spring:
  config:
    import: env.yml
  datasource:
    url: jdbc:postgresql://${SERVER_ADDRESS}:${POSTGRESQL.PORT}/relpl
    username: ${POSTGRESQL.NAME}
    password: ${POSTGRESQL.PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      url: mongodb://${SERVER_ADDRESS}:${MONGODB.PORT}
      host: ${SERVER_ADDRESS}
      port: ${MONGODB.PORT}
      database: ${MONGODB.NAME}
    redis:
      host: ${SERVER_ADDRESS}
      port: ${REDIS.PORT}

tmap:
  api:
    key: ${TMAP_KEY}

cloud:
  aws:
    s3:
      bucket: ${AWS.BUCKET_NAME}
      base-url: https://${AWS.BUCKET_NAME}.s3.ap-northeast-2.amazonaws.com/
    credentials:
      access-key: ${AWS.ACCESS_KEY}
      secret-key: ${AWS.SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false